# Autostart apps
# Not sure if this does anything
exec-once = hyprctl setcursor Adwaita 10

# Audio
exec-once = pipewire

# Desktop
exec-once = mako
exec-once = hyprpaper
exec-once = hypridle
exec-once = waybar

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# My services
exec-once = power-profile-auto

# Restore hardware state
exec-once = sleep 3; hardware-state restore

# Autostart apps
exec-once = sleep 3; $terminal
exec-once = sleep 4; $terminal

