$launcher = fuzzel
$terminal = kitty
$betterterminal = ghostty
$browser = chromium --enable-features=UseOzonePlatform --ozone-platform=wayland

bind = SUPER, SPACE, exec, $launcher
bind = SUPER, RETURN, exec, $betterterminal
bind = SUPER, G, exec, $betterterminal
bind = SUPER, T, exec, $terminal
bind = SUPER, V, exec, launcher-clipboard
bind = SUPER, O, exec, launcher-files
#bind = SUPER, B, exec, firefox&
bind = SUPER, B, exec, $browser
bind = SUPER, Q, killactive
bind = SUPER, M, exit

# Screen shotting
bind = SUPER_SHIFT, S, exec, hyprshot -m region
bind = SUPER_SHIFT, W, exec, hyprshot -m window
bind = SUPER_SHIFT, M, exec, hyprshot -m output
bind = SUPER ALT SHIFT, S, exec, hyprshot -m region --clipboard-only
bind = SUPER ALT SHIFT, W, exec, hyprshot -m window --clipboard-only
bind = SUPER ALT SHIFT, M, exec, hyprshot -m output --clipboard-only

# MBA brightness keys
# Screen brightness
bindel = , XF86MonBrightnessUp, exec, brightness-up
bindel = , XF86MonBrightnessDown, exec, brightness-down

# Keyboard backlight
bindel = , XF86KbdBrightnessUp, exec, kbd-brightness-up
bindel = , XF86KbdBrightnessDown, exec, kbd-brightness-down

# MBA volume keys
bindel = , XF86AudioRaiseVolume, exec, volume-up
bindel = , XF86AudioLowerVolume, exec, volume-down
bindl  = , XF86AudioMute, exec, volume-toggle

# Workspaces
# Switch directly to workspaces 1 through 5
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

