# Design customizations
general {
    gaps_in = 3
    gaps_out = 6
    border_size = 1
}

decoration {
    rounding = 3

    shadow {
        enabled = false
        range = 12
        render_power = 3
        color = rgba(00e5ffee)
    }
}

