env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = QT_QPA_PLATFORM,wayland
env = GDK_BACKEND,wayland
env = MOZ_ENABLE_WAYLAND,1
env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,10
#env = HYPRCURSOR_THEME,Adwaita
#env = HYPRCURSOR_SIZE,10

exec-once = hyprctl setcursor Adwaita 10

exec-once = pipewire

exec-once = mako
exec-once = hyprpaper
exec-once = hypridle
exec-once = waybar

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

$launcher = fuzzel
$terminal = kitty
$betterterminal = ghostty
$browser = chromium --enable-features=UseOzonePlatform --ozone-platform=wayland
$clipboard = cliphist list | fuzzel --dmenu | cliphist decode | wl-copy
bind = SUPER, SPACE, exec, $launcher
bind = SUPER, RETURN, exec, $betterterminal
bind = SUPER, G, exec, $betterterminal
bind = SUPER, T, exec, $terminal
bind = SUPER, V, exec, $clipboard
#bind = SUPER, B, exec, firefox&
bind = SUPER, B, exec, $browser
bind = SUPER, Q, killactive
bind = SUPER, M, exit

# Screen shotting
bind = SUPER_SHIFT, S, exec, hyprshot -m region
bind = SUPER_SHIFT, W, exec, hyprshot -m window
bind = SUPER_SHIFT, M, exec, hyprshot -m output
bind = SUPER ALT SHIFT, S, exec, hyprshot -m region --clipboard-only
bind = SUPER ALT SHIFT, W, exec, hyprshot -m window --clipboard-only
bind = SUPER ALT SHIFT, M, exec, hyprshot -m output --clipboard-only

# MBA volume keys
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

general {
    gaps_in = 3
    gaps_out = 6
    border_size = 1
}

decoration {
    rounding = 3

    shadow {
        enabled = false
        range = 12
        render_power = 3
        color = rgba(00e5ffee)
    }
}

# Workspaces
# Switch directly to workspaces 1 through 5
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10


