general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hardware-state restore # use our custom hardware-state
}

listener {
    timeout = 10 # 120 # 180
    on-timeout = brightnessctl --device='*kbd_backlight*' set 0
    on-resume = hardware-state restore
}

listener {
    timeout = 12 # 180 # 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && hardware-state restore
}

listener {
    timeout = 14 # 300
    on-timeout = loginctl lock-session
}

