input {
    kb_layout = us

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        tap-to-click = false
        tap-and-drag = false
        clickfinger_behavior = true
        scroll_factor = 0.7
    }
}
