# Nice fixed size
$fixed_size=size 1000 760
$fixed_opacity=opacity 0.8 0.7

# Yazi
windowrule = match:title ^Yazi$, float on, center on, $fixed_size, $fixed_opacity

# Lazygit
windowrule = match:title ^Lazygit$, float on, center on, $fixed_size, $fixed_opacity

# Pulsemixer
windowrule = match:title ^Pulsemixer$, float on, center on, $fixed_opacity

# Bluetui
windowrule = match:title ^Bluetui$, float on, center on, $fixed_opacity

# Nmtui
windowrule = match:title ^Nmtui$, float on, center on, $fixed_opacity

