# Yazi
windowrule = match:title ^Yazi$, float on, center on, size 1000 760, opacity 0.8 0.7

# Lazygit
windowrule = match:title ^Lazygit$, float on, center on, size 1000 760, opacity 0.8 0.7

# Pulsemixer
windowrule = match:title ^Pulsemixer$, float on, center on, size 1000 760, opacity 0.8 0.7

# Bluetui
windowrule = match:title ^Bluetui$, float on, center on, size 1000 760, opacity 0.8 0.7

# Nmtui
windowrule = match:title ^Nmtui$, float on, center on, size 1000 760, opacity 0.8 0.7

