# ~/.config/fuzzel/fuzzel.ini

[main]
font=Inter:size=7.5
terminal=ghostty
prompt="❯ "
icon-theme=Papirus-Dark

icons-enabled=no
show-actions=no

width=52
lines=10

horizontal-pad=22
vertical-pad=14
inner-pad=12
line-height=14

layer=overlay
dpi-aware=yes

[border]
width=1
radius=3

[colors]
background=000000f2
text=d8d8d8ff

match=00e5ffff

selection=161616ff
selection-text=ffffffff
selection-match=00e5ffff

border=00e5ffff
