background {
    color = rgb(000000)
}

input-field {
    size = 220, 36
    position = 0, -40
    dots_center = true
    font_family = Inter
    font_size = 8
    outer_color = rgb(00e5ff)
    inner_color = rgb(000000)
    font_color = rgb(f8fafc)
    outline_thickness = 1
}
